cfg_file: ''
criterion:
  type: cross_entropy
data:
  args: []
  dataset: cifar10
  file_path: ''
  load_all_dataset: true
  root: /mnt/workspace/colla_group/data/
  save_data: false
  splitter: 'dirichlet'
  splitter_args: [{'beta':0.1}]
  target_transform: []
  test_pre_transform: []
  test_target_transform: []
  test_transform: []
  transform: []
  val_pre_transform: []
  val_target_transform: []
  val_transform: []
device: 0
eval:
  batchsize: 128
  freq: 1
expname: ""
expname_tag: 'loss_classify'
federate:
  client_num: 10
  generic_fl_eval: false
  method: local
  restore_from: ''
  sample_client_num: 10
  sample_mode: random
  save_to: ''
  total_round_num: 100
  use_hetero_model: True
client_resource:
  dataset: 
    "0": cifar10
    "1": cifar10
    "2": cifar10
    "3": cifar10
    "4": cifar10
    "5": cifar10
    "6": cifar10
    "7": cifar10
    "8": cifar10
    "9": cifar10
  backbone: 
    "0": ResNet50Cifar10
    "1": ResNet50Cifar10
    "2": ResNet50Cifar10
    "3": ResNet50Cifar10
    "4": ResNet50Cifar10
    "5": ResNet18Cifar10
    "6": ResNet18Cifar10
    "7": ResNet18Cifar10
    "8": ResNet18Cifar10
    "9": ResNet18Cifar10
  encoder_list:
    "0": ["linear"]
    "1": ["linear"]
    "2": ["linear"]
    "3": ["linear"]
    "4": ["linear"]
    "5": ["linear"]
    "6": ["linear"]
    "7": ["linear"]
    "8": ["linear"]
    "9": ["linear"]
  encoder_para_list: 
    "0": ["in_dim",2048,"out_dim",512]
    "1": ["in_dim",2048,"out_dim",512]
    "2": ["in_dim",2048,"out_dim",512]
    "3": ["in_dim",2048,"out_dim",512]
    "4": ["in_dim",2048,"out_dim",512]
    "5": ["in_dim",512,"out_dim",512]
    "6": ["in_dim",512,"out_dim",512]
    "7": ["in_dim",512,"out_dim",512]
    "8": ["in_dim",512,"out_dim",512]
    "9": ["in_dim",512,"out_dim",512]
  head_list:
    "0": ["linear"]
    "1": ["linear"]
    "2": ["linear"]
    "3": ["linear"]
    "4": ["linear"]
    "5": ["linear"]
    "6": ["linear"]
    "7": ["linear"]
    "8": ["linear"]
    "9": ["linear"]
  head_para_list: 
    "0": ["in_dim",512,"out_dim",10]
    "1": ["in_dim",512,"out_dim",10]
    "2": ["in_dim",512,"out_dim",10]
    "3": ["in_dim",512,"out_dim",10]
    "4": ["in_dim",512,"out_dim",10]
    "5": ["in_dim",512,"out_dim",10]
    "6": ["in_dim",512,"out_dim",10]
    "7": ["in_dim",512,"out_dim",10]
    "8": ["in_dim",512,"out_dim",10]
    "9": ["in_dim",512,"out_dim",10]
fm:
  use: false
grad:
  grad_accum_count: 1
  grad_clip: -1.0
model:
  backbone: ResNet18Cifar10
  dropout: 0.5
  encoder_list: ["identity"]
  encoder_para_list: []
  head_list: ["linear"]
  head_para_list: ["in_dim", 512, "out_dim", 10]
  hidden: 256
  in_channels: 0
  input_shape: []
  out_channels: 1
outdir: /mnt/workspace/lisiyi/exp_out/local/
print_decimal_digits: 6
regularizer:
  mu: 0.0
  type: ''
seed: 0
tqn_train:
  key_train_round: 160
train:
  batch_or_epoch: batch
  batchsize: 128
  local_update_steps: 1
  optimizer:
    lr: 0.001
    momentum: 0.9
    type: Adam
    weight_decay: 0.0
  scheduler:
    type: ''
    warmup_ratio: 0.0
use_gpu: True
verbose: 1

